source 'https://rubygems.org'

ruby '>= 3.4.0'

gem 'cocoapods', '1.16.2'
gem 'xcodeproj', '1.27.0'
gem 'activesupport', '7.2.3.1'
# Libraries removed from the Ruby 3.4+ standard library that CocoaPods still loads.
gem 'bigdecimal', '4.0.1'
gem 'logger', '1.7.0'
gem 'benchmark', '0.5.0'
gem 'mutex_m', '0.3.0'
gem 'nkf', '0.2.0'
